version: "3.7"
services:
  app:
    image: avaliarh:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - avaliarh_network
    environment:
      - DATABASE_URL=postgresql://postgres:02e821629ceff274c853f24327a36132@postgres:5432/avaliacao_candidatos
      - NEXTAUTH_SECRET=1cb8ab490649f272b366a6343f0e223c
      - NEXTAUTH_URL=https://avaliacao.doutoranimal.com.br
    restart: always
    depends_on:
      - postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.avaliarh.rule=Host(`avaliacao.doutoranimal.com.br`)
        - traefik.http.routers.avaliarh.entrypoints=websecure
        - traefik.http.routers.avaliarh.tls.certresolver=letsencryptresolver
        - traefik.http.services.avaliarh.loadbalancer.server.port=3000
        - traefik.http.services.avaliarh.loadbalancer.passHostHeader=true
        - traefik.http.routers.avaliarh.service=avaliarh

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - avaliarh_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=02e821629ceff274c853f24327a36132
      - POSTGRES_DB=avaliacao_candidatos
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  setup:
    image: avaliarh:latest
    command: sh -c "npx prisma migrate deploy && node prisma/seed.js"
    environment:
      - DATABASE_URL=postgresql://postgres:02e821629ceff274c853f24327a36132@postgres:5432/avaliacao_candidatos
    networks:
      - avaliarh_network
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  postgres_data:
    external: true
    name: avaliarh_postgres_data

networks:
  avaliarh_network:
    external: true
    name: ralliugaNet
