version: "3.7"
services:
  app:
    image: node:18
    entrypoint: ["/bin/bash", "-c"]
    command: [
      "rm -rf /tmp/app && git clone https://github.com/jeanjonathas/avaliarh.git /tmp/app && cd /tmp/app && npm install --no-fund --no-audit --legacy-peer-deps && npx prisma generate && (cp /opt/avaliarh/.env /tmp/app/.env || echo '.env not found as file') && node scripts/setup-db-config.js && npx prisma migrate deploy && npx prisma db seed && npm run build && NODE_ENV=production npm run start"
    ]
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-02e821629ceff274c853f24327a36132}@avaliarh_postgres:5432/${POSTGRES_DB:-avaliacao_candidatos}?schema=public
      - NODE_ENV=production
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-02e821629ceff274c853f24327a36132}
      - NEXTAUTH_URL=https://admitto.com.br
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXT_PUBLIC_DOMAIN=admitto.com.br
      - NEXT_PUBLIC_COOKIE_PREFIX=prod_
    volumes:
      - /opt/avaliarh/.env:/opt/avaliarh/.env
    networks:
      - public
    depends_on:
      avaliarh_postgres:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.enable=true
        - traefik.http.routers.avaliarh.rule=Host(`admitto.com.br`) || Host(`admitto.app`)
        - traefik.http.routers.avaliarh.entrypoints=websecure
        - traefik.http.routers.avaliarh.tls=true
        - traefik.http.routers.avaliarh.tls.certresolver=myresolver
        - traefik.http.services.avaliarh.loadbalancer.server.port=3000

  avaliarh_postgres:
    image: postgres:15-alpine
    container_name: avaliarh_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - public
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-02e821629ceff274c853f24327a36132}
      - POSTGRES_DB=${POSTGRES_DB:-avaliacao_candidatos}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: avaliarh_postgres_data

networks:
  public:
    external: true
    name: traefik-public